services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "GOOS=${GOOS}"
      - "GOARCH={GOARCH}"
    image: poptape/admin/api:v0.1
    ports:
      - "1264:9300"
    restart: always
    volumes:
      - ${LOCAL_LOG_LOC}:/admin/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    depends_on:
      - admin_db
    networks:
      - poptape
  admin_db:
    image: postgres:alpine
    restart: always
    ports:
      - "1265:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - poptape_admin_data:/var/lib/postgresql/data
    networks:
      - poptape
networks:
  poptape:
    external: true
volumes:
  poptape_admin_data: