name: Build and test
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * 1' # run "At 10:00 on Monday"

jobs:
  api-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      volumes:
        - ${{ github.workspace }}:/go/src/github.com/cliveyg/poptape-admin
    defaults:
      run:
        working-directory: /go/src/github.com/cliveyg/poptape-admin
    services:
      pdb:
        image: postgres
        env:
          POSTGRES_DB: poptape_admin_test
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_TESTDB_PASSWORD }}"
          POSTGRES_USER: poptape_admin_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mdb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: poptape_admin_backups_test
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_TESTDB_ROOT_PASSWORD }}
          MONGO_INITDB_DATABASE: poptape_admin_backups_test
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20
        env:
          SERVICES: s3,iam # Add more services as needed
          DEBUG: 1

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localstack:4566

    steps:
      - name: Install ca certs dependency
        run: |
          apt-get update && apt-get install --yes --no-install-recommends ca-certificates

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Run go build
        run: go build -o /dev/null ./...

      - name: Create .env file from github secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy .env into all package directories
        run: |
          find . -type d -exec cp .env {}/.env \;

      - name: Install bc
        run: apt-get update && apt-get install --yes --no-install-recommends bc

      # all tests:
      - name: Run tests and generate test coverage file (excluding tests and testutils from coverage report)
        run: |
          set -e
          set -o pipefail
          touch poptape_admin.log
          # go test -v -cover -coverprofile=cover.out ./tests -run '^TestListAllPoptapeStandardBuckets_FailNoS3_DEV' | tee test.out
          go test -v ./... -cover -coverpkg=./... -coverprofile=cover.out | tee test.out
          grep -v '/tests/' cover.out | grep -v '/testutils/' > cover.out.filtered
          mv cover.out.filtered cover.out
        shell: bash

      - name: Check test coverage is above threshold
        env:
          TESTCOVERAGE_THRESHOLD: 0
        run: |
          echo "Checking test coverage is above threshold..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=$(go tool cover -func=cover.out | awk '/^total:/ {gsub("%","",$3); print $3}')
          echo "Current test coverage : $totalCoverage %"
          echo "-----------------------------------------------------------"
          if [ "$(echo "$totalCoverage >= $TESTCOVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
            echo "Coverage passed threshold OK"
          else
            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
            echo "Failed"
            exit 1
          fi
          echo "-----------------------------------------------------------"
        shell: bash

      - name: Show coverage summary
        run: go tool cover -func=cover.out

      - name: Generate HTML coverage report
        run: |
          go tool cover -html=cover.out -o coverage.html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Install gcov2lcov
        run: go install github.com/jandelgado/gcov2lcov@latest

      - name: Convert Go cover.out to lcov.info
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gcov2lcov -infile cover.out -outfile coverage.lcov

      - name: Create coverage badges
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: c9188881d498a3e609cfcf4875845d9f
          token: ${{ secrets.GIST_TOKEN }}