name: Build and test
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * 1' # run "At 10:00 on Monday"

jobs:
  unit-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      volumes:
        - ${{ github.workspace }}:/go/src/github.com/cliveyg/poptape-admin
    defaults:
      run:
        working-directory: /go/src/github.com/cliveyg/poptape-admin
    services:
      # label used to access the service container
      pdb:
        image: postgres
        env:
          POSTGRES_DB: poptape_admin_test
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_TESTDB_PASSWORD }}"
          POSTGRES_USER: poptape_admin_test
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mdb:
        # dockerhub image
        image: mongo
        # provide the login and db deets for mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: poptape_admin_backups_test
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_TESTDB_ROOT_PASSWORD }}
          MONGO_INITDB_DATABASE: poptape_admin_backups_test
        ports:
          # maps tcp port 27017 on service container to the host
          - 27017:27017
        # set health checks to wait until mongo has started
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # add install ca certs step to prevent tls error messages
      # when installing golang deps
      - name: Install ca certs dependency
        run: |
          apt-get update && apt-get install --yes --no-install-recommends ca-certificates

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install Go dependencies
        run: |
          go mod tidy

      # run go build and output binary to dev null as it's not used for running unit tests
      - name: Run go build
        run: go build -o /dev/null ./...

      # have to create an .env file to be able to run unit tests
      - name: Create .env file from github secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy .env into all package directories
        run: |
          find . -type d -exec cp .env {}/.env \;

      # Install bc for floating-point comparison in coverage check
      - name: Install bc
        run: apt-get update && apt-get install --yes --no-install-recommends bc

      # run unit tests
      - name: Run go test and generate test coverage file
        run: |
          set -e
          set -o pipefail
          touch poptape_admin.log
          go test -v ./... -cover -coverpkg=./... -coverprofile=cover.out | tee test.out
        shell: bash

      # and check test coverage percentage
      - name: Check test coverage is above threshold
        env:
          TESTCOVERAGE_THRESHOLD: 15
        run: |
          echo "Checking test coverage is above threshold..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=$(go tool cover -func=cover.out | awk '/^total:/ {gsub("%","",$3); print $3}')
          echo "Current test coverage : $totalCoverage %"
          echo "-----------------------------------------------------------"
          if [ "$(echo "$totalCoverage >= $TESTCOVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
            echo "Coverage passed threshold OK"
          else
            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
            echo "Failed"
            exit 1
          fi
          echo "-----------------------------------------------------------"
        shell: bash

      - name: Show coverage summary
        run: go tool cover -func=cover.out

      # Generate HTML coverage report
      - name: Generate HTML coverage report
        run: |
          go tool cover -html=cover.out -o coverage.html

      # Upload HTML coverage report as an artifact so you can download it after the workflow run
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Create coverage badges
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: c9188881d498a3e609cfcf4875845d9f
          token: ${{ secrets.GIST_TOKEN }}
          coverage-file: cover.out
          coverage-format: go